---
abstract: 'Catmandu modules for working with OCLC web services'
author:
  - 'Patrick Hochstenbach, C<< <patrick.hochstenbach at ugent.be> >>'
build_requires:
  Module::Build: '0.3601'
  Test::More: '1.001003'
  Test::Simple: '1.001003'
configure_requires:
  Module::Build: '0.3601'
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.5, Dist::Zilla version 5.016, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Catmandu-OCLC
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Catmandu: '0.9202'
  LWP::Simple: '6.00'
  Moo: '1.0'
  URI::Escape: '1.60'
  perl: v5.10.1
resources:
  bugtracker: https://github.com/LibreCat/Catmandu-OCLC/issues
  homepage: https://github.com/LibreCat/Catmandu-OCLC
  repository: https://github.com/LibreCat/Catmandu-OCLC.git
version: '0.002'
